# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your challenges, our solutions | WANTED.solutions
email: ping@wanted.solutions
keywords: "WANTED.solutions, IT solutions, web development, app development, video production, graphic design, digital agency, creativity driven, innovation, stunning cinematography"
subject: WANTED.solutions is creativity driven digital agency that offers innovative IT solutions and stunning cinematography for your business. Whether you need a website, an app, a video, or a graphic design, we have the skills and the vision to make it happen. We are passionate about creating digital products that are user-friendly, engaging, and effective. We work with clients from various industries and sectors, delivering tailor-made solutions that meet their needs and goals. At WANTED.solutions, we don't just provide services, we create solutions for your challenges.
google_analytics: G-HT4PQ5J6CC
description: >- # this means to ignore newlines until "baseurl:"
  WANTED.solutions is creativity driven digital agency that offers innovative IT solutions and stunning cinematography for your business. Whether you need a website, an app, a video, or a graphic design, we have the skills and the vision to make it happen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wanted.solutions" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  wanted-solutions
http_csp: "default-src 'self'; font-src 'self' data: fonts.gstatic.com; script-src 'self' 'unsafe-inline' www.googletagmanager.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src https://*; connect-src 'self' *.google-analytics.com; child-src 'none';"

sass:
    sass_dir: _sass
    style: compressed


paginate: 12
paginate_path: "/articles:num/"
# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
